---
title: "Bayes Implementation"
output: html_document
---

```{r packages, include = FALSE}
library(tidyverse)
library(silounloadr)
library(kippcolors)
library(janitor)
library(lubridate)
library(caret)
library(broom)
library(parsnip)
library(recipes)
library(modelr)
library(tidymodels)
library(brms)
theme_set(theme_kipp_light())


bigrquery::set_service_token("kipp-chicago-silo-2-aa786970aefd.json")
```


```{r knitr_options, results='hide', echo=FALSE}
knitr::opts_knit$set(comment = FALSE,
                     warning = FALSE, 
                     progress = FALSE, 
                     verbose = FALSE
                     )
```

```{r att_mem_tables, cache=TRUE, results='hide', echo=FALSE}
membership <- get_powerschool("ps_membership_reg") %>% 
  select(studentid,
         schoolid,
         date = calendardate,
         enrolled = studentmembership,
         grade_level,
         attendance = ATT_CalcCntPresentAbsent,
         yearid) %>%
  filter(yearid >= 25)


attendance <- get_powerschool("attendance") %>% 
  filter(yearid >= 25,
        att_mode_code == "ATT_ModeDaily") 

attendance_code <- get_powerschool("attendance_code") %>%
  mutate(att_code = if_else(att_code == "true", "T", att_code)) %>% 
  select(attendance_codeid = id,
         att_code)
  
  
```


```{r students, cache=TRUE, include=FALSE}
students <- get_powerschool("students") %>% 
  select(studentid = id, 
         student_number,
         gender,
         entrydate,
         schoolentrydate,
         districtentrydate,
         geocode) %>%
  collect()
  
```


```{r joining_tables, results='hide', echo=FALSE, cache=TRUE}
member_att <- membership %>% 
  dplyr::left_join(attendance %>% 
              select(-schoolid,
                        -yearid) %>% 
              dplyr::left_join(attendance_code,
                        by = "attendance_codeid"),
            by = c("studentid",
                   "date" = "att_date")) %>% 
  collect()

```

```{r recoding, results='hide', echo=FALSE}

student_att <- member_att %>%
  mutate(enrolled0 = 1,
         enrolled = if_else(att_code == "D" & !is.na(att_code), 0, enrolled0),
         present0 = ifelse(is.na(att_code), 1, 0),
         present1 = ifelse(att_code %in%  c("A", "S"), 0, present0),
         present2 = ifelse(att_code == "H", 0.5, present1),
         present3 = ifelse(att_code %in% c("T", "E", "I"), 1, present2),
         present = ifelse(is.na(present2), 1, present3),
         absent = (1 - present)*enrolled,
         tardy = ifelse(att_code %in% "T", 1, 0),
         dna0 = if_else(att_code == "D", 1, 0),
         dna = if_else(is.na(dna0), 0, dna0)) %>%
  select(yearid,
         schoolid,
         studentid,
         grade_level,
         date,
         att_code,
         enrolled,
         present,
         absent,
         tardy,
         dna)


```



```{r cumulative quantities of interest}
yearly_ada <- student_att %>% 
  filter(yearid < 28) %>%
  group_by(yearid,
           studentid) %>% 
  summarize(enrolled = sum(enrolled),
            absent = sum(absent),
            year_end = 1 - (absent/enrolled))
 
cum_ada <- student_att %>% 
  filter(yearid < 28) %>%
  group_by(yearid,
           studentid) %>% 
  arrange(date) %>% 
  mutate(cum_enrolled = cumsum(enrolled),
         cum_absent = cumsum(absent),
         running_ada = 1 - (cum_absent/cum_enrolled)) %>% 
  filter(cum_enrolled > 0)

yearly_cum_ada <- cum_ada %>% 
  select(yearid,
         schoolid,
         grade_level,
         studentid,
         date,
         cum_enrolled,
         cum_absent,
         running_ada) %>% 
  dplyr::left_join(yearly_ada %>% 
              select(-c(enrolled,
                        absent)),
            by = c("yearid",
                   "studentid"))


```


```{r dec_subset}
year_end_date <- yearly_cum_ada %>% 
  group_by(yearid) %>% 
  select(date) %>% 
  distinct() %>% 
  filter(date == max(date))

dec_dates <- yearly_cum_ada %>% 
  group_by(yearid) %>% 
  select(date) %>% 
  distinct() %>% 
  filter(lubridate::month(date) == 12) %>% 
  filter(date == max(date))

yca_filtered_dec <- yearly_cum_ada %>% 
  inner_join(dec_dates %>% 
               ungroup() %>% 
               select(-yearid),
             by = c("date")) %>%
  ungroup() %>%
  mutate(yearid = as.factor(yearid),
         schoolid = as.factor(schoolid))

yca_filtered_yr_end <- yearly_cum_ada %>% 
  inner_join(year_end_date %>% 
               ungroup() %>% 
               select(-yearid),
             by = c("date")) %>%
  ungroup() %>%
  mutate(yearid = as.factor(yearid),
         schoolid = as.factor(schoolid)) %>% 
  select(yearid,
         schoolid,
         studentid,
         yr_end_enrolled = cum_enrolled,
         yr_end_absent = cum_absent)

yca_filtered <- yca_filtered_dec %>% 
  inner_join(yca_filtered_yr_end,
             by = c("yearid",
                    "schoolid",
                    "studentid")) %>% 
  mutate(yr_end_present = yr_end_enrolled - yr_end_absent,
         cum_present = cum_enrolled - cum_absent)

```


```{r recipes}
yca_cont <- yca_filtered %>% #continuous var only
  select(-c(yearid,
            grade_level,
            date)) %>% 
  mutate(studentid = as_factor(studentid))

bayes_recipe <- yca_cont %>% 
  recipe(year_end ~ .) %>% 
  step_center(all_numeric()) %>% 
  step_scale(all_numeric()) %>% 
  prep()


bayes_data <- bayes_recipe %>% 
  juice()


```


```{r}
fit1 <- brm(year_end ~ cum_enrolled + cum_absent + (1|schoolid),
            bayes_data,
            family = gaussian(link = "identity"))


```



